#### Importando Libreria Numpy


In [4]:
import numpy as np

#### Creando una lista de 10 elemntos

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Transformando la lista a un Array

In [6]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Corroborando el tipo de objeto

In [7]:
type(arreglo)

numpy.ndarray

#### Corroborando el tipo de dato del arreglo

In [8]:
arreglo.dtype

dtype('int32')

#### Definiendo el Array de int32 a float32

In [9]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### Sigue siendo un array de int32

In [11]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Transformando los datos de int32 a float32

In [12]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### Obteniendo el promedio del array

In [13]:
promedio = np.mean(arreglo)
promedio

5.5

#### Obteniendo la media del array

In [16]:
mediana = np.median(arreglo)
mediana

5.5

#### Desviacion estandar del arreglo

In [14]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

#### Generación de un arreglo de 10 elementos de solo unos

In [5]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Generación de un arreglo de 10 elementos de solo ceros

In [6]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

#### Transformando el arreglo de unos de punto flotante a enteros

In [7]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### UTILIZANDO LA FUNCIÓN RANDOM

#### Generando arreglo aleatorio de 5 elementos

In [9]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 

array([0.15666714, 0.35762232, 0.67757038, 0.48565636, 0.34410022,
       0.2768297 , 0.67789831, 0.4736516 , 0.12916839, 0.81271443])

#### Generando una matriz aleatoria de 3x3

In [10]:
matriz = np.random.rand(3,3)
matriz

array([[0.7559158 , 0.55045648, 0.16482733],
       [0.13186072, 0.36931405, 0.29914275],
       [0.97988919, 0.44308394, 0.59448342]])

#### Generando un arreglo aleatorio de 10 números enteros del 1 al 5

In [11]:
arreglo_aleatorio2  = np.random.randint(1,1001,5)
arreglo_aleatorio2

array([623, 658, 173, 570, 974])

#### Generando una matriz aleatoria de 10 números enteros del 1 al 100

In [12]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[30, 59, 66, 48, 14, 87,  1, 29, 82, 72],
       [67, 85, 26, 94, 55, 78, 26, 85, 64, 54],
       [76, 59, 59, 21, 48, 77, 82,  8, 19, 23],
       [46, 48, 72, 33, 90, 56, 79, 16, 29,  2],
       [76, 59, 72, 47, 87,  8, 36, 59, 30, 17],
       [75, 68, 95, 17, 48, 64, 82, 61, 16, 51],
       [30, 85, 11, 89, 16, 75, 94,  4, 24, 54],
       [50, 91, 77, 34, 46, 65, 98, 34, 85, 92],
       [18, 63, 46, 96, 79, 38, 56, 35, 58, 32],
       [64, 20, 18, 68, 14, 36, 11, 78, 11, 24]])